name: Deploy with cloudformation

on:
  workflow_dispatch:

jobs:

  create-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: deploy web server infrastructure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: eu-central-1
        run: |
          cd cloudformation
          aws cloudformation create-stack --stack-name my-web-server-stack --template-body file://web-server-stack.yml
